/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FestivalTag = { 'ganeshPuja' : null } |
  { 'wedding' : null } |
  { 'birthday' : null } |
  { 'diwali' : null } |
  { 'dussehra' : null } |
  { 'rakhi' : null };
export interface Inquiry {
  'id' : bigint,
  'inquiryType' : InquiryType,
  'name' : string,
  'email' : string,
  'message' : string,
  'productInterest' : string,
  'phone' : string,
}
export type InquiryType = { 'retail' : null } |
  { 'wholesale' : null };
export interface Product {
  'id' : bigint,
  'festivalTag' : [] | [FestivalTag],
  'name' : string,
  'isWholesaleAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'price' : [] | [bigint],
}
export type ProductCategory = { 'ganeshPujaItems' : null } |
  { 'photoMala' : null } |
  { 'radhaKrishnaPujaItems' : null } |
  { 'murtiDecoration' : null } |
  { 'birthdayEventDecor' : null } |
  { 'chundriFabrics' : null } |
  { 'weddingAccessories' : null } |
  { 'decorativePapers' : null } |
  { 'thermocolItems' : null } |
  { 'photoFraming' : null } |
  { 'artificialFlowers' : null } |
  { 'rakhiCollection' : null };
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [
      string,
      string,
      ProductCategory,
      [] | [bigint],
      string,
      boolean,
      boolean,
      [] | [FestivalTag],
    ],
    bigint
  >,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getProductsByFestivalTag' : ActorMethod<[FestivalTag], Array<Product>>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
  'seedSampleProducts' : ActorMethod<[], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, InquiryType, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];