/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'ganeshPujaItems' : IDL.Null,
  'photoMala' : IDL.Null,
  'radhaKrishnaPujaItems' : IDL.Null,
  'murtiDecoration' : IDL.Null,
  'birthdayEventDecor' : IDL.Null,
  'chundriFabrics' : IDL.Null,
  'weddingAccessories' : IDL.Null,
  'decorativePapers' : IDL.Null,
  'thermocolItems' : IDL.Null,
  'photoFraming' : IDL.Null,
  'artificialFlowers' : IDL.Null,
  'rakhiCollection' : IDL.Null,
});
export const FestivalTag = IDL.Variant({
  'ganeshPuja' : IDL.Null,
  'wedding' : IDL.Null,
  'birthday' : IDL.Null,
  'diwali' : IDL.Null,
  'dussehra' : IDL.Null,
  'rakhi' : IDL.Null,
});
export const InquiryType = IDL.Variant({
  'retail' : IDL.Null,
  'wholesale' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'festivalTag' : IDL.Opt(FestivalTag),
  'name' : IDL.Text,
  'isWholesaleAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : ProductCategory,
  'price' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ProductCategory,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(FestivalTag),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByFestivalTag' : IDL.Func(
      [FestivalTag],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedSampleProducts' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, InquiryType, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'ganeshPujaItems' : IDL.Null,
    'photoMala' : IDL.Null,
    'radhaKrishnaPujaItems' : IDL.Null,
    'murtiDecoration' : IDL.Null,
    'birthdayEventDecor' : IDL.Null,
    'chundriFabrics' : IDL.Null,
    'weddingAccessories' : IDL.Null,
    'decorativePapers' : IDL.Null,
    'thermocolItems' : IDL.Null,
    'photoFraming' : IDL.Null,
    'artificialFlowers' : IDL.Null,
    'rakhiCollection' : IDL.Null,
  });
  const FestivalTag = IDL.Variant({
    'ganeshPuja' : IDL.Null,
    'wedding' : IDL.Null,
    'birthday' : IDL.Null,
    'diwali' : IDL.Null,
    'dussehra' : IDL.Null,
    'rakhi' : IDL.Null,
  });
  const InquiryType = IDL.Variant({
    'retail' : IDL.Null,
    'wholesale' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'festivalTag' : IDL.Opt(FestivalTag),
    'name' : IDL.Text,
    'isWholesaleAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : ProductCategory,
    'price' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ProductCategory,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(FestivalTag),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByFestivalTag' : IDL.Func(
        [FestivalTag],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedSampleProducts' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, InquiryType, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };