/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Inquiry {
    id: bigint;
    inquiryType: InquiryType;
    name: string;
    email: string;
    message: string;
    productInterest: string;
    phone: string;
}
export interface Product {
    id: bigint;
    festivalTag?: FestivalTag;
    name: string;
    isWholesaleAvailable: boolean;
    description: string;
    imageUrl: string;
    isFeatured: boolean;
    category: ProductCategory;
    price?: bigint;
}
export enum FestivalTag {
    ganeshPuja = "ganeshPuja",
    wedding = "wedding",
    birthday = "birthday",
    diwali = "diwali",
    dussehra = "dussehra",
    rakhi = "rakhi"
}
export enum InquiryType {
    retail = "retail",
    wholesale = "wholesale"
}
export enum ProductCategory {
    ganeshPujaItems = "ganeshPujaItems",
    photoMala = "photoMala",
    radhaKrishnaPujaItems = "radhaKrishnaPujaItems",
    murtiDecoration = "murtiDecoration",
    birthdayEventDecor = "birthdayEventDecor",
    chundriFabrics = "chundriFabrics",
    weddingAccessories = "weddingAccessories",
    decorativePapers = "decorativePapers",
    thermocolItems = "thermocolItems",
    photoFraming = "photoFraming",
    artificialFlowers = "artificialFlowers",
    rakhiCollection = "rakhiCollection"
}
export interface backendInterface {
    addProduct(name: string, description: string, category: ProductCategory, price: bigint | null, imageUrl: string, isFeatured: boolean, isWholesaleAvailable: boolean, festivalTag: FestivalTag | null): Promise<bigint>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getFeaturedProducts(): Promise<Array<Product>>;
    getProduct(id: bigint): Promise<Product>;
    getProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    getProductsByFestivalTag(tag: FestivalTag): Promise<Array<Product>>;
    searchProductsByName(name: string): Promise<Array<Product>>;
    seedSampleProducts(): Promise<void>;
    submitInquiry(name: string, phone: string, email: string, message: string, inquiryType: InquiryType, productInterest: string): Promise<bigint>;
}
import type { FestivalTag as _FestivalTag, Inquiry as _Inquiry, InquiryType as _InquiryType, Product as _Product, ProductCategory as _ProductCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: string, arg1: string, arg2: ProductCategory, arg3: bigint | null, arg4: string, arg5: boolean, arg6: boolean, arg7: FestivalTag | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProducts();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProducts();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByFestivalTag(arg0: FestivalTag): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByFestivalTag(to_candid_FestivalTag_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByFestivalTag(to_candid_FestivalTag_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProductsByName(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProductsByName(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProductsByName(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleProducts();
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: InquiryType, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, to_candid_InquiryType_n21(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, to_candid_InquiryType_n21(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
}
function from_candid_FestivalTag_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FestivalTag): FestivalTag {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FestivalTag]): FestivalTag | null {
    return value.length === 0 ? null : from_candid_FestivalTag_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    festivalTag: [] | [_FestivalTag];
    name: string;
    isWholesaleAvailable: boolean;
    description: string;
    imageUrl: string;
    isFeatured: boolean;
    category: _ProductCategory;
    price: [] | [bigint];
}): {
    id: bigint;
    festivalTag?: FestivalTag;
    name: string;
    isWholesaleAvailable: boolean;
    description: string;
    imageUrl: string;
    isFeatured: boolean;
    category: ProductCategory;
    price?: bigint;
} {
    return {
        id: value.id,
        festivalTag: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.festivalTag)),
        name: value.name,
        isWholesaleAvailable: value.isWholesaleAvailable,
        description: value.description,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: from_candid_ProductCategory_n18(_uploadFile, _downloadFile, value.category),
        price: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.price))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inquiryType: _InquiryType;
    name: string;
    email: string;
    message: string;
    productInterest: string;
    phone: string;
}): {
    id: bigint;
    inquiryType: InquiryType;
    name: string;
    email: string;
    message: string;
    productInterest: string;
    phone: string;
} {
    return {
        id: value.id,
        inquiryType: from_candid_InquiryType_n10(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        email: value.email,
        message: value.message,
        productInterest: value.productInterest,
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retail: null;
} | {
    wholesale: null;
}): InquiryType {
    return "retail" in value ? InquiryType.retail : "wholesale" in value ? InquiryType.wholesale : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ganeshPuja: null;
} | {
    wedding: null;
} | {
    birthday: null;
} | {
    diwali: null;
} | {
    dussehra: null;
} | {
    rakhi: null;
}): FestivalTag {
    return "ganeshPuja" in value ? FestivalTag.ganeshPuja : "wedding" in value ? FestivalTag.wedding : "birthday" in value ? FestivalTag.birthday : "diwali" in value ? FestivalTag.diwali : "dussehra" in value ? FestivalTag.dussehra : "rakhi" in value ? FestivalTag.rakhi : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ganeshPujaItems: null;
} | {
    photoMala: null;
} | {
    radhaKrishnaPujaItems: null;
} | {
    murtiDecoration: null;
} | {
    birthdayEventDecor: null;
} | {
    chundriFabrics: null;
} | {
    weddingAccessories: null;
} | {
    decorativePapers: null;
} | {
    thermocolItems: null;
} | {
    photoFraming: null;
} | {
    artificialFlowers: null;
} | {
    rakhiCollection: null;
}): ProductCategory {
    return "ganeshPujaItems" in value ? ProductCategory.ganeshPujaItems : "photoMala" in value ? ProductCategory.photoMala : "radhaKrishnaPujaItems" in value ? ProductCategory.radhaKrishnaPujaItems : "murtiDecoration" in value ? ProductCategory.murtiDecoration : "birthdayEventDecor" in value ? ProductCategory.birthdayEventDecor : "chundriFabrics" in value ? ProductCategory.chundriFabrics : "weddingAccessories" in value ? ProductCategory.weddingAccessories : "decorativePapers" in value ? ProductCategory.decorativePapers : "thermocolItems" in value ? ProductCategory.thermocolItems : "photoFraming" in value ? ProductCategory.photoFraming : "artificialFlowers" in value ? ProductCategory.artificialFlowers : "rakhiCollection" in value ? ProductCategory.rakhiCollection : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_FestivalTag_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FestivalTag): _FestivalTag {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FestivalTag | null): [] | [_FestivalTag] {
    return value === null ? candid_none() : candid_some(to_candid_FestivalTag_n5(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    ganeshPujaItems: null;
} | {
    photoMala: null;
} | {
    radhaKrishnaPujaItems: null;
} | {
    murtiDecoration: null;
} | {
    birthdayEventDecor: null;
} | {
    chundriFabrics: null;
} | {
    weddingAccessories: null;
} | {
    decorativePapers: null;
} | {
    thermocolItems: null;
} | {
    photoFraming: null;
} | {
    artificialFlowers: null;
} | {
    rakhiCollection: null;
} {
    return value == ProductCategory.ganeshPujaItems ? {
        ganeshPujaItems: null
    } : value == ProductCategory.photoMala ? {
        photoMala: null
    } : value == ProductCategory.radhaKrishnaPujaItems ? {
        radhaKrishnaPujaItems: null
    } : value == ProductCategory.murtiDecoration ? {
        murtiDecoration: null
    } : value == ProductCategory.birthdayEventDecor ? {
        birthdayEventDecor: null
    } : value == ProductCategory.chundriFabrics ? {
        chundriFabrics: null
    } : value == ProductCategory.weddingAccessories ? {
        weddingAccessories: null
    } : value == ProductCategory.decorativePapers ? {
        decorativePapers: null
    } : value == ProductCategory.thermocolItems ? {
        thermocolItems: null
    } : value == ProductCategory.photoFraming ? {
        photoFraming: null
    } : value == ProductCategory.artificialFlowers ? {
        artificialFlowers: null
    } : value == ProductCategory.rakhiCollection ? {
        rakhiCollection: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    retail: null;
} | {
    wholesale: null;
} {
    return value == InquiryType.retail ? {
        retail: null
    } : value == InquiryType.wholesale ? {
        wholesale: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FestivalTag): {
    ganeshPuja: null;
} | {
    wedding: null;
} | {
    birthday: null;
} | {
    diwali: null;
} | {
    dussehra: null;
} | {
    rakhi: null;
} {
    return value == FestivalTag.ganeshPuja ? {
        ganeshPuja: null
    } : value == FestivalTag.wedding ? {
        wedding: null
    } : value == FestivalTag.birthday ? {
        birthday: null
    } : value == FestivalTag.diwali ? {
        diwali: null
    } : value == FestivalTag.dussehra ? {
        dussehra: null
    } : value == FestivalTag.rakhi ? {
        rakhi: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
